function keyword(id){var keyword=document.getElementById(id);var value=keyword.value;var defaultValue=keyword.value;var defaultColor=keyword.style.color;keyword.onfocus=function(){if(this.value==defaultValue){this.value="";this.style.color="#444"
if(this.getAttribute("reType")=="password")this.setAttribute("type","password")}};keyword.onblur=function(){if(this.value==''){if(this.getAttribute("reType")=="password")this.setAttribute("type","text")
this.value=defaultValue;this.style.color=defaultColor}};};function showAlert(id){$("#"+id).show();$("#"+id).css({top:($(window).height()-$("#"+id).outerHeight())/2+$(document).scrollTop()});}
$(function(){$(".alert .close").click(function(){$(this).parent().parent().hide();})
$("#mainSearch li").click(function(){$(this).addClass("current").siblings().removeClass();})
if(document.getElementById("searchKey"))keyword("searchKey");if(document.getElementById("findName"))keyword("findName");if(document.getElementById("findEmail"))keyword("findEmail");jQuery(".slideBox").slide({mainCell:".bd ul",effect:"top",autoPlay:true});$("#trTable1 tr:even").addClass("even");$("#trTable2 tr:even").addClass("even");$("#ymDetial .table2 tr:even").addClass("even");var accordion_head=$('.accordion > li > a'),accordion_body=$('.accordion li > .sub-menu');accordion_head.first().addClass('active').next().slideDown('normal');accordion_head.on('click',function(event){event.preventDefault();if($(this).attr('class')!='active'){accordion_body.slideUp('normal');$(this).next().stop(true,true).slideToggle('normal');accordion_head.removeClass('active');$(this).addClass('active');}});$("#ymDetial .sold .bt").click(function(){if($("#ymDetial .table").hasClass('show')){$("#ymDetial .table").slideUp('normal');$("#ymDetial .table").removeClass('show');}
else{$("#ymDetial .table").addClass('show');$("#ymDetial .table").slideDown('normal');}})
$('#memberMenu > dd.hide').hide();$("#memberMenu .menu").click(function(){if($(this).next().hasClass('show')){$('dd.show').removeClass('show').addClass('hide').slideUp();}else{$('dd.show').removeClass('show').addClass('hide').slideUp();$(this).next().removeClass('hide').addClass('show').slideDown();}})
$("#hotKey .bt").click(function(){if($(this).hasClass('show')){$("#hotKey .detailBg").animate({height:32,width:964});$(this).removeClass('show');}
else{$("#hotKey .detailBg").animate({height:$("#hotKey .detail").height()+8,width:998});$(this).addClass('show');}});})